### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by vfuse** [goenning/nixstats-js#1]
I'm getting the following error on Debain 8 and Mac OSx

TypeError: Cannot read property 'replace' of undefined

root@nixstats-dev0:~# node --version
v6.2.2
root@nixstats-dev0:~# nodejs --version
v0.10.29

**Comment by goenning** [comment]
I'll add a debug flag because simple error messages are not enough for errors like this. But as I remember I'm using same node version on my Mac and it's working.

**Comment by goenning** [comment]
@vfuse can you please update and try again?

**Comment by vfuse** [comment]
Seems to be working now, cool!

**Comment by goenning** [comment]
Nice! Feel free to open issues with suggestions or sending a PR. I'll add memory and disk usage to `now` command, because that's what I mostly look at.
